### ISSUE TITLE
请问有演示视频吗，使用vscode运行的吗

### ISSUE THREAD

**Issue by rodrickcui** [2017403603/My_Net_Sniffer#1]

**Comment by 2017403603** [comment]
有运行视频，不过是通过idea运行的，视频里面有我私人信息，所以就没有公布了，我记得代码是可以直接运行的，vscode配一下环境就行了




李航程
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2017403603/My_Net_Sniffer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月19日(星期一) 晚上10:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [2017403603/My_Net_Sniffer] 请问有演示视频吗，使用vscode运行的吗 (Issue #1)





 
Closed #1 as completed.
